services:
  zeek:
    build: .
    container_name: SIMIR_Z
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      ZEEK_INTERFACE: enx000ec89f6cc0
    volumes:
      - ./logs:/usr/local/zeek/spool/zeek
      - ./site:/usr/local/zeek/share/zeek/site
      - /etc/localtime:/etc/localtime:ro
    command: >
      sh -c "/usr/local/bin/entrypoint.sh"
    restart: unless-stopped